.TH simple-rpg 6 08-30-2010 Longwood simple-rpg
.SH NAME
	simple-rpg \- A simple Unix role-playing game.

.SH SYNOPSIS
.RI simple-rpg 
[num_objects] 
[num_moving_objects]

.SH DESCRIPTION
	This is a simple role-playing game in which a player moves around an
11x11 grid in search of various objects.  Each object has a value.  The player
can take objects to increase his score by their value.  The game also features
moving objects called monsters which the player can fight to further increase
his score. 

The game controls are: “i” for up, “j” for left, “m” for down, “k” for right, "t" to take an object, and “q” for quit.

.SH OPTIONS
.TP 8
.B num_objects
Specify how many objects to place on the board.
.TP 8
.B num_moving_objects
Specify how many of the objects should be moving objects.
